version: '3.7'

services:
  db:
    image: mcr.microsoft.com/mssql/server
    container_name: db
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=sa12345!
    volumes:
      - database:/var/opt/mssql
  apigtw: 
    container_name: ApiGateway
    build:
        context: ./TeamManager.ApiGateway/
        dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "5005:5005"
    volumes:
      - ./TeamManager.ApiGateway:/app
    environment:
      - 'ConnectionStrings:TeamManager=server=db,1433;database=TeamManager;User Id=sa;Password=sa12345!;MultipleActiveResultSets=True'
      - 'ASPNETCORE_URLS=http://*:5005'
      - 'DOTNET_USE_POLLING_FILE_WATCHER=1'
    depends_on:
      - db
  people:
    container_name: PeopleService
    build:
      context: ./TeamManager.PeopleService/
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./TeamManager.PeopleService:/app
    environment:
      - 'ConnectionStrings:TeamManager=server=db,1433;database=TeamManager;User Id=sa;Password=sa12345!;MultipleActiveResultSets=True'
      - 'ASPNETCORE_URLS=http://*:80'
      - 'DOTNET_USE_POLLING_FILE_WATCHER=1'
    depends_on:
      - db
  feedback:
    container_name: FeedbackService
    build:
      context: ./TeamManager.FeedbackService/
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./TeamManager.FeedbackService:/app
    environment:
      - 'ConnectionStrings:TeamManager=server=db,1433;database=TeamManager;User Id=sa;Password=sa12345!;MultipleActiveResultSets=True'
      - 'ASPNETCORE_URLS=http://*:80'
      - 'DOTNET_USE_POLLING_FILE_WATCHER=1'
    depends_on:
      - db
  ui:
    container_name: UI
    build:      
      context: ./TeamManager.UI/
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./TeamManager.UI/src:/home/app/angular-app/src
    depends_on:
      - db
      - people
volumes: 
  database: 
